ohmybash/oh-my-bash

plugins/aws/aws.plugin.sh

This small plugin makes it easier to work with multiple AWS profiles. It adds two commands (agp and asp) to get and set the current AWS profile.

First version of AWS plugin

---

templates/bashrc.osh-template

This PR fixes https://github.com/ohmybash/oh-my-bash/issues/18
Oh My Bash should not be executed on noninteractive shells.

Only execute oh-my-bash on an interactive shell in .bashrc

---

plugins/bu/bu.plugin.sh

"bu 3" will take the user 3 folders up => cd ../../../
I believe this will add a fast way for users to change directory up and unlike the method used in aliases, this method is not limited to a specific number of predefined aliases.

Add 'bu' function to CD up faster

---

oh-my-bash.sh
tools/install.sh

Checks the version of bash before installing oh-my-bash. It's a ticky for new users to navigate if they end up in this state and hence a basic check.
See comments here - 
https://github.com/ohmybash/oh-my-bash/issues/27

Fix to check bash version before install

---

themes/base.theme.sh

set "function" before append_prompt_override in line 521 so that bash could known the command

function append_prompt_override

---

plugins/bashmarks/README.md
plugins/bashmarks/bashmarks.plugin.sh

Accept just a bookmark name as a short form of the '-g' option.  If just
one arg is supplied, and it doesn't start with a dash, then it is assumed
to be a bookmark name and _goto_bookmark is called. [ bm BOOKMARK_NAME ]
Add a -h option to print usage info with same behavior as supplying no args
Add echoing an error message if an unrecognized option is given, followed
by usage info
Augment usage info to reflect these changes and update README.md
(this is my first public contribution in a while.  I tried my best to read and follow conventions.)

Add short form of '-g' option to bashmarks plugin

---

lib/theme-and-appearance.sh

Setting the color is ok, but the alias should be set on another place.
Refs #106

Remove using of the alias command in theme and appearance.

---

plugins/battery/battery.plugin.sh

This should handle `command_exists()` if function is not pulled from `lib/base.sh` -> plugin will define it by itself.
@antofthy Please test
Fixes: https://github.com/ohmybash/oh-my-bash/issues/68

plugins/battery: Attempt to fix #68

---

lib/utils.sh

Fixed by suggestion 
https://github.com/ohmybash/oh-my-bash/issues/68#issuecomment-523238232
Bug: https://github.com/ohmybash/oh-my-bash/issues/68

lib/utils: Code quality improvement

---

aliases/general.aliases.sh

- This alias resets the terminal in cases where `stty sane` and reset may not work.  From [wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code): 
> This will reset the console, similar to the command reset on modern Linux systems; however it should work even on older Linux systems and on other (non-Linux) UNIX variants.

aliases/general: Add fix_term alias to reset the terminal

---

themes/agnoster/agnoster.theme.sh

Changes in prompt_virtualenv() function inside of agnoster theme, in order to show the venv python version and not the venv folder name.

themes/agnoster: Changes in Agnoster theme

---

themes/powerline/powerline.base.sh

This PR fixes #36.
The powerline theme implicitly assumes that bash's IFS (internal field seperator) contains a space character. This is used to iterate of the space seperated list stored in `${POWERLINE_PROMPT} `i.e.
```
for segment in ${POWERLINE_PROMPT}; do
local info="$(__powerline_${segment}_prompt)"
[[ -n "${info}" ]] && __powerline_left_segment "${info}"
done
```
In case any application changes the IFS to not contain a space, instead of a proper powerline bash prompt, one gets the error message `__powerline_user_info scm python_venv cwd_prompt: command not found`
This PR fixes this issue by setting the IFS explicitly when splitting the space seperated string into an array.

themes/powerline: Fix powerline theme implicitly depends on bash's IFS

---

themes/agnoster/agnoster.theme.sh

* Make sure that the output of `python --version` is always captured.
* Refactor logic to extract Python version using `awk` instead of a
for-loop.

themes/agnoster: Prompt broken when using pyenv (#176)

---

plugins/git/git.plugin.sh

Add two aliases to autostash local changes while rebasing. Those were very useful when I was using oh-my-zsh, and were missed when I migrated to oh-my-bash.

plugins/git: add git pull autostash aliases

---

LICENSE.md
README.md

The MIT license does not allow to remove the original copyright notice. See #151.

Fix the violation of the MIT license of Oh My Zsh

---

themes/base.theme.sh

Underscore characters in git branch names are displayed in the scm prompt as hypens, so e.g. my_branch becomes my-branch.
This change adds the _ character to the branch name character whitelist

Add '_' to git branch name character whitelist

---

oh-my-bash.sh

The “:t” construct is part of history expansion, whereas here we’re doing
parameter expansion.

oh-my-bash.sh: fix reading of custom/lib files

---

lib/grep.sh

Previously, only the first element of the array was expanded, which is
always the empty string, so the setting of GREP_OPTIONS was useless. Expand
the entire array.

lib/grep.sh: fix expansion of GREP_OPTIONS

---

lib/utils.sh
oh-my-bash.sh
plugins/sdkman/sdkman.plugin.sh
plugins/zoxide/zoxide.plugin.sh
themes/base.theme.sh
themes/powerline/powerline.base.sh

The original function `type_exists` uses the option `-P` that limits the scope of the search to commands defined by files.
When debugging why the battery plugin was not working, I figured out that, also when the plugin was loaded, the function was overwritten by:
```
if ! type_exists 'battery_charge' ; then
function battery_charge (){
echo -n
}
fi
```
The issue is that`battery_charge` is defined as a function in the `battery` plugin and `type_exists` return `false`.
This PR expands the search scope (via the `-t` option) to:
-   alias (command is shell alias)
-   keyword (command is shell reserved word)
-   function (command is shell function)
-   builtin (command is shell builtin)
-   file (command is disk file)

lib/utils: Include functions when searching for a command

---

tools/install.sh
tools/uninstall.sh

Fix #213. There are several issues in the current install script. This PR tries to fix them. I separated commits for each fixes as follows. Thank you.
As I have already commented in ***, `tput` may support `termcap` names instead of `terminfo` names depending on the system.
Also, I have changed `which` to `hash` as is later used to test `git`. `which` is not a POSIX utility, so it may be missing.  `hash` is a builtin command of Bash so always available while running in Bash.
The right-hand sides of assignments is not subject to word splitting or pathname expansions, so quotation is unneeded for the command substitutions.
```
[ -n $BASH_VERSION ]
```
In Bash and POSIX shells (unlike the default of Zsh), the unquoted parameter expansion `$BASH_VERSION` is subject to word splitting and …

Fix install script for #213

---

lib/omb-deprecate.sh
lib/utils.sh
oh-my-bash.sh

We want to make use of our utility functions defined in a script file also from other script files. However, the loading order of script files matters for such a situation. Currently, we don't have a way to control the loading order. For example, in order to use `_omb_util_command_exists` (`lib/utils.sh`) from other script files in `lib/` as suggested in #239, we need to load `lib/utils.sh`  earlier than the other files.
We here introduce new functions `_omb_module_require{,_lib,_plugin,_alias,_completion,_theme}` that can be used to declare the dependencies in each module.

oh-my-bash: Add a function for dependency resolution and refactor

---

tools/install.sh

Now the script uses logging functions.
Use substring removal parameter expansion to get the BASH major version.
Run sed in place on the bashrc file, instead of outputting to a file and
force copying over the original.
Wrapped loose variables in '"' to prevent globbing and word splitting.

Refactored install.sh

---

lib/functions.sh
tools/install.sh
tools/uninstall.sh

This fixes the issue reported at #115 and #267. We should not overwrite the existing backup file. In this PR, I take the approach suggested by @alexpfx in #115; The backup filename now contains the timestamp. Also, in recovering the original bashrc, we search for the latest backed-up `.bashrc` that does not contain `source oh-my-bash.sh`. Additionally, the code of `chsh -s bash` in uninstallation, which makes sense only for `oh-my-zsh`, has been removed.
----
Resolve #267 / Resolve #115

Do not overwrite backup bashrc

---

tools/upgrade.sh

Fixes #245. See also the discussion in 028d2537392a5e1ec8166600105840e107eb65c9.

tools/upgrade: Return to the original working directory after upgrading

---

lib/bourne-shell.sh

Do not use eval and export LESSOPEN directly only when is empty.
This will prevent problems on distributions using different lesspipe
and/or defining LESSOPEN variable on their own.
Issue #46 #69
----
Fixes #46 / Fixes #69 / Fixes #296

Fix exporting LESSOPEN

---

themes/rana/rana.theme.sh

Fixes #248 
I'm definitely no bash expert, so there may be a better solution to this. I took the idea of the `ansi` function in the agnoster theme.
See my comment in #248

rana: Fixing #248

---

README.md

This clone line fails with:
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

Update repo link

---

lib/bourne-shell.sh
lib/directories.sh
lib/grep.sh
lib/misc.sh
lib/utils.sh
templates/bashrc.osh-template

Fixes #304.
Currenty, oh-my-bash currently overrides any aliases that has been set for `ls`, `grep`, `egrep`, and `fgrep`, if the file `/usr/bin/dircolors` exists.
This means if a user specifies any aliases before OMB is sourced, they will be overwritten in a manner which is non transparent to the user (It is not stated anywhere, and the user cannot explicitly disabled it).
The goal of this PR is to not overwrite the aliases if they already exist, preferring the pre-defined aliases instead.
Alternatively, a means of disabling the new OMB aliases could be introduced through an environment variable, to allow the user to not have them set.
Currently, it wraps each alias call in an `if` statement, to check if they exist prior to applying them.
But, as per suggestions from akinomyoga, a …

Fixes user defined aliases being overridden by OMB 

---

completions/awscli.completion.sh
completions/conda.completion.sh
completions/django.completion.sh
completions/docker-compose.completion.sh
completions/docker-machine.completion.sh
completions/docker.completion.sh
completions/drush.completion.sh
completions/fabric-completion.sh
completions/gh.completion.sh
completions/hub.completion.sh
completions/jungle.completion.sh
completions/kontena.completion.sh
completions/kubectl.completion.sh
completions/maven.completion.sh
completions/minikube.completion.sh
completions/npm.completion.sh
completions/packer.completion.sh
completions/system.completion.sh
lib/base.sh
lib/misc.sh
lib/omb-prompt-base.sh
lib/utils.sh
plugins/battery/battery.plugin.sh
plugins/nvm/nvm.plugin.sh
themes/brainy/brainy.theme.sh
themes/dulcie/dulcie.theme.sh
tools/autossh.sh
tools/install.sh

Debian has deprecated usage of `which`, as per:
https://salsa.debian.org/debian/debianutils/-/commit/3a8dd10b4502f7bae8fc6973c13ce23fc9da7efb
The recommendation is now to use `command -v`.

Replace `which` with `command -v`

---

lib/omb-prompt-base.sh

git_status_flags variable wasn't in the function git_prompt_vars, so if `set -u` was set in bashrc, it would give unbound variable error constantly.

Fixed unbound variable error

---

plugins/xterm/xterm.plugin.bash

On ubuntu 20 LTS I was getting syntax error (line 23) when the plugin was activated.
I fixed set-title sequence (to ESC0;titleBEL), where ESC is \e (or \033) and BEL is \a (or \007).

fixes in xterm plugin to make it work

---

themes/sirup/sirup.theme.sh

Added the ability to show the current Virtual Env when using Python Virtual Env. 
If there's not vitual env, the theme works normal.

themes/sirup: Show VirtualEnv

---

lib/omb-prompt-base.sh
lib/omb-prompt-colors.sh
themes/axin/axin.theme.sh
themes/sexy/sexy.theme.sh

Added functionality to display the name of an active Conda environment for `themes/sexy`. Functionality is generalizable to all other themes.
- Edited `_omb_theme_PROMPT_COMMAND()` to check for whether a Conda environment is active (If there is a conda environment active, then `$CONDA_SHLVL == 1`)
- Resolved environment name in the `$PS1` variable by invoking `$(basename $CONDA_DEFAULT_ENV)`
- colorized it to match the theme
This is what it looks like when you activate a Conda environment, and after you deactivate a Conda environment:

themes/sexy: display active conda environment's name in bash prompt

---

lib/shopt.sh

The CASE_SENSITIVE setting was not being checked when setting case-insensitive globbing / matching.  Add checks in the appropriate places, preserving the default (insensitive) behaviour unless explicitly
changed.
Further, this will also apply to expansions so that case-sensitivity will apply in an intuitive way, treating paths, filename completions and command completions consistently.
Signed-off-by: Joe MacDonald <joe.macdonald@siemens.com>
This is a rework of #180 attempting to simplify the code there a bit, squash the commits together and address the remaining open suggestion in it.  It's not intended to address the hyphenation / underscore feature in #383 since that seems like a separate discussion and probably warrants a separate setting.  I don't see hyphenation and case sensitivity …

Rework PR#180 to address comments and add case sensitivity to command completion

---

lib/shopt.sh
templates/bashrc.osh-template

Adjusted shopt.sh to use CASE_SENSITIVe and HYPHEN_INSENSITIVE variables to affect completion.
Note, this changes the old default hyphen insensitive completion behavior, the user will need to set HYPHEN_INSENSITIVE="true" to have the old default behavior

Allow CASE_SENSITIVE and HYPHEN_INSENSITIVE to work as documented

---

lib/omb-prompt-base.sh

Add "." to the git branch character whitelist to fix branches like v6.0 or 5.4.2, as examples.
I'm working with a branch that is called "toradex_5.4-2.3.x-imx" from the linux-toradex repo. It was get renamed to "toradex_5-4-2-3-x-imx", which is very annoying. This also passed the https://github.com/njhartwell/pw3nage test.

omb-prompt-base: Add "." to git branch whitelist

---

lib/history.sh

OMB currently sets in `lib/history.sh`:
```
HISTCONTROL="erasedups:ignoreboth"
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"
```
According to [official GNU bash manual](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#index-HISTIGNORE), having `&:[ ]*` in `HISTIGNORE` provides the functionality of `ignoreboth`. Thus, having both provides redundant results but makes the config harder to understand.

Removing redundant HISTIGNORE patterns

---

lib/history.sh

`shopt -s histappend` is executed twice in `lib/history.sh` with just 12 lines in between, which do not really do anything but define a single variable (`HISTFILE`). No reason to have this twice:
```bash
$ grep -n 'shopt -s histappend' ~/.oh-my-bash/lib/history.sh
2:shopt -s histappend # append to bash_history if Terminal.app quits
14:shopt -s histappend
$
```

Removed redundant shopt command (histappend)

---

completions/svn.completion.sh
lib/git.sh
lib/omb-prompt-base.sh
plugins/git/git.plugin.sh
themes/agnoster/agnoster.theme.sh
themes/cooperkid/cooperkid.theme.sh
themes/cupcake/cupcake.theme.sh
themes/doubletime/doubletime.theme.sh
themes/hawaii50/hawaii50.theme.sh
themes/mbriggs/mbriggs.theme.sh
themes/rana/rana.theme.sh
themes/sexy/sexy.theme.sh

This was largely done correctly, but several invocations of “git” were not
done with “command”. This means that they could pick up aliases for git,
such as “hub” or “lab”, which would still work, but (especially with “lab”)
make things really slow.

base.theme.sh: use “command” to run git and svn everywhere

---

themes/agnoster/agnoster.theme.sh
themes/doubletime/doubletime.theme.sh

```c++
bash: git_status_dirty: command not found
bash: git_stash_dirty: command not found
```
git_status_dirty and git_stash_dirty are functions and not external command but are internal functions in given file.

agnoster theam out of box reports "command not found"

---

plugins/battery/battery.plugin.sh

Getting data from /sys directory will make it easier for battery plugin to work even if none of the commands tried in function [ac_adapter_connected](https://github.com/ohmybash/oh-my-bash/blob/89e505415284619377df9d8dc73f033572e24621/plugins/battery/battery.plugin.sh#L6) are available, for ex. in a docker container.

Added other ways to get adapter and battery status.

---

lib/shopt.sh
themes/agnoster/agnoster.theme.sh
themes/roderik/roderik.theme.sh
themes/vscode/vscode.theme.sh

This change will allow a user to export the PROMPT_DIRTRIM variable in
their .bashrc and change the prompt path length.

lib, themes: Preserve users' PROMPT_DIRTRIM

---

lib/directories.sh

The 1 .. 9 aliases in `lib/directories.sh` work now.
$ cd aa
$ cd bb
$ cd cc
$ d
1    ~/cc
2    ~/bb
3    ~/aa
$ 3
$ pwd
~/aa
$ d
1    ~/aa
2    ~/cc
3    ~/bb

lib/directories: Add `cd` function, a clone of Zsh cd builtin command

---

completions/django.completion.sh
completions/gh.completion.sh
completions/hub.completion.sh
completions/vagrant.completion.sh
completions/vault.completion.sh
lib/omb-prompt-base.sh
lib/readlink.sh
lib/utils.sh
themes/agnoster/agnoster.theme.sh
themes/duru/duru.theme.sh
themes/hawaii50/hawaii50.theme.sh

Improve quoting in various areas.
I also had the chance to reproduce #242, but it seems like the issue has been fixed since then. So closes #242

fix: Quoting

---

lib/omb-prompt-base.sh

I noticed this when checking out the n0qorg, being outside a git repository would have an undecorated `detached:` (from `SCM_THEME_DETACHED_PREFIX`) in the prompt.  It's easy enough to correct this in the theme but since the problem also may be observed in hawaii50, iterate, pro, standard and zitron as well, and `git rev-parse` is fast to execute anyway, this seems to be the correct place to insert this quick check.

omb-prompt-base: do not attempt to process git vars outside a git tree

---

lib/omb-prompt-base.sh
templates/bashrc.osh-template

Add `SCM_GIT_DISABLE_UNTRACKED_DIRTY="true"` setting for `lib/omb-prompt-base.sh` to disable consideration repos with untracked files as dirty.

Setting to disable consideration repos with untracked files as dirty

---

themes/agnoster/agnoster.theme.sh

At the moment, agnoster relies on `$VIRTUAL_ENV` to detect virtualenvs, but it is unreliable when using pyenv. With a named pyenv virtualenv, it properly detects we are in a virtualenv, and sets the prompt as `[v] <version>`; when using a non-system version, it fails to detect the version (`$VIRTUAL_ENV` is not set) and hides the python segment.
Ideally (I think), pyenv should be treated and displayed somewhat like conda is: when a non system version is used, grab the python version, and when in a virtualenv, show its name and version.
This PR adds Pyenv detection to agnoster:
- if pyenv is not initialized, fall back to the virtualenv detection
- when pyenv is set to a version other than "system", show the version number
- when pyenv is in virtulenv mode, also display the virtualenv's …

themes/agnoster : pyenv not properly detected/shown

---

completions/rake.completion.sh

My rake (13.0.6) generates empty list for completition without the flag `--all`

Update rake.completion.sh to list all tasks

---

completions/capistrano.completion.sh
completions/homesick.completion.sh
completions/rake.completion.sh
completions/sdkman.completion.sh
completions/ssh.completion.sh
lib/omb-completion.sh

Fix #471
The main change is commit 3da4bf6. This PR contains other refactoring and indentation changes.

completions/{ssh,rake,capistrano}: Do not rewrite `COMP_WORDBREAKS`

---

.github/workflows/format.yml

This uses `actions/setup-go` to install Go. The minimum required version is now 1.20 as per [this](https://github.com/editorconfig/editorconfig-core-go/commit/73c37c49c298ff5a605f2a07228f3f99acf3d2d8) commit in [editorconfig-core-go](https://github.com/editorconfig/editorconfig-core-go).
Fixes an issue mentioned in #484

ci: Use `setup-go` to install Go v1.20

---

completions/gh.completion.sh
completions/git_flow.completion.sh
completions/git_flow_avh.completion.sh
completions/hub.completion.sh
lib/git.sh
lib/omb-prompt-base.sh
lib/utils.sh
oh-my-bash.sh
themes/agnoster/agnoster.theme.sh
themes/cooperkid/cooperkid.theme.sh
themes/cupcake/cupcake.theme.sh
themes/doubletime/doubletime.theme.sh
themes/hawaii50/hawaii50.theme.sh
themes/mbriggs/mbriggs.theme.sh
themes/pzq/pzq.theme.sh
themes/rana/rana.theme.sh
themes/sexy/sexy.theme.sh
themes/vscode/vscode.theme.sh

This also includes refactoring.
- 779d5fada73e401357a63d727bb7291e42bad495 The main fix for the uses of Zsh constructs.
- e2a9fae9274abde0be6ae8889c44dc4f22ae9cd0 This is to avoid a conflict with the same name of a function defined in another file.
- 960ac2596f68145f48feb0b035d9a226da52ddac This makes the invocation of `command git` for prompts and completions indirect through the function `_omb_prompt_git`. This will be a base for #428 and #173. As far as we directly call `command git`, we need to specify the command modifications for timeouts and git settings for every invocation of `command git`, which is not useful.
- ad07989f4abfa3c6c5fc311e917bf5f78de2470d A utility function to split a string safely.
- a4e0ca1ec9f46f07480a4c6361973c6ff1918fdd and …

lib/git: Fix problems caused by uses of Zsh features

---

lib/history.sh

There does not seem to be a specific reason that we export HISTIGNORE as mentioned in https://github.com/ohmybash/oh-my-bash/discussions/500#discussioncomment-7676355.  These lines were introduced in commit 53fb8037 but only HISTIGNORE had `export`.
In this PR, I try to remove the redundant `export` from the definition of `HISTIGNORE`. I'll wait for a while. If anyone has a reason to export HISTIGNORE, please let me know in this PR.

lib/history: remove redundant export for HISTIGNORE

---

plugins/nvm/nvm.plugin.sh

Fixes #504
This PR applies the changes introduced in https://github.com/nvm-sh/nvm/pull/2017. I skip the upstream changes introduced in https://github.com/nvm-sh/nvm/pull/2313 and in https://github.com/nvm-sh/nvm/pull/3082.
@ffd114 Could you check this branch (`nvm-update` branch at `akinomyoga/oh-my-bash`)?

lib/nvm: update autoloader to keep up with the upstream

---

lib/shopt.sh

The setting `shopt -s nocasematch` affects every pattern matching in Bash including the case statement, `[[ str == pat ]]` matching, `${var/pat/rep}`, and `${var#pat}`.  Since the affected range is too large, this potentially breaks the existing functions.  I think this setting `shopt -s nocasematch` should be enabled locally when it is specifically needed rather than enabling it globally.
----
These settings seem to have been introduced in #399 where the proper support for `CASE_SENSITIVE` was attempted. Before this PR, only `nocaseglob` has been specified in OMB.
@jjmcdn Could you take a look at this PR? Since you have introduced `nocasematch`, I need to check the background and motivations of making `nocasematch` controlled by `CASE_SENSITIVE`. As I've described above, `nocasematch` …

lib/shopt: remove nocasematch

---

aliases/README.md
aliases/package-manager.aliases.bash

Removed 'ers', improved 'emfu', added 'ec'.

Improve aliases of portage

---

themes/THEMES.md
themes/powerline-icon/powerline-icon.base.sh
themes/powerline/powerline.base.sh

Fixed Bugs: 
- An error in one of the powerline functions has been corrected, which was preventing the display of the icon for a successfully executed command.

Error correction in the powerline-icon theme

---

themes/mairan/mairan.theme.sh
themes/zork/zork.theme.sh

Without double-quotes, paths with spaces are not resolved correctly and venv name is not displayed correctly.
Before: 
```
└─▪ echo $VIRTUAL_ENV
~/Documents/Path with spaces/env
basename: extra operand ‘spaces/env’
Try 'basename --help' for more information.
┌─()[name][os][±][( main ?:3 ⊘ )][~<Path redacted>]
```
But with this small change: 
```
┌─(env)[name][os][±][( main ?:3 ⊘ )][~<Path redacted>]
└─▪
```
Edit: I'm not super familiar with Bash, but I'd recommend a quick once-over to make sure this issue doesn't appear in other places for zork. I only really discoverd this because of novice-level Bash knowledge and ChatGPT xd.

Resolve VIRTUAL_ENV with double-quotes

---

CONTRIBUTING.md
plugins/README.md

I added a readme that has a small overview of what each of the plugins does and included information on how to install them.👀

plugins: Add README.md

---

themes/90210/README.md
themes/axin/README.md
themes/bakke/README.md
themes/binaryanomaly/README.md
themes/bobby/README.md

*_I plan to do it with everyone but I wanted the approval to continue working **!**_*

themes/90210..bobby: Add README.md

---

completions/ssh.completion.sh
lib/utils.sh

From 7.3p1 and up, there is an Include keyword, which allows you to include additional configuration files.  
>Include  
Include the specified configuration file(s).  Multiple pathnames may be specified and each pathname may contain glob(3) wildcards and, for user configurations, shell-like “~” references to user home directories.  Files without absolute paths are assumed to be in ~/.ssh if included in a user configuration file or /etc/ssh if included from the system configuration file.  Include directive may appear inside a Match or Host block to perform conditional inclusion.
Source: [ssh_config(5)](http://man7.org/linux/man-pages/man5/ssh_config.5.html).
So if you have `Include config.d/*` in your `~/.ssh/config` file, this pull request allows files put in `~/.ssh/config.d/` to be also …

feat: add support for ssh completion using files in .ssh/config.d too

---

completions/ssh.completion.sh

Partial fix for https://github.com/ohmybash/oh-my-bash/issues/568

completions/ssh: Include global ssh hosts

---

tools/update-wiki-themes.sh

I got bored, and I was looking through OMB themes, when I noticed that there were a great many discrepancies between the "Themes" page in Wiki and the "themes" folder in this repo...
tl;dr: I scripted an update process for the Wiki file that uses content as it currently exists inside this repo.
but I found I was still bored, so I made it configurable via either environment variables or CLI args.. and documented it's usage at the top of the script.
then I tested it a whole bunch to make sure I couldn't break it..
anyways, question for the repo maintainers: would this perhaps be helpful to you guys?
---
note: this does require one small change to the `Themes.md` file, specifically as follows:
```diff
diff --git a/Themes.md b/Themes.md
index 9917bb2..4e77dca 100644
--- a/Themes.md
+++ …
```

add Wiki "Themes" page updater script

---

completions/asdf.completion.sh
plugins/README.md
plugins/asdf/README.md
plugins/asdf/asdf.plugin.sh

This adds a plugin to load the [asdf version manager](https://github.com/asdf-vm/asdf) through *oh-my-bash*. It's roughly based off of the [original pull request](https://github.com/ohmybash/oh-my-bash/pull/310), moves to the bash syntax, and allows checking for the `ASDF_DIR` variable before hitting the file system.
```
asdf plugin add nodejs
asdf install nodejs latest
```

plugins/asdf: Add `asdf` extendable version manager plugin

---

plugins/README.md
plugins/colored-man-pages/README.md
plugins/colored-man-pages/colored-man-pages.plugin.sh

Inspired by the [`colored-man-pages`](https://github.com/ohmyzsh/ohmyzsh/tree/a72a26406ad3aa9a47c3f5227291bad23494bed0/plugins/colored-man-pages) zsh plugin.
This is likely not the best design, as I'm grabbing the specific colors. If there's a better method, feel free to let me know.

Add Colored Man Pages plugin

---

lib/grep.sh

Checks if the desired _grep_ option is available, properly.
Executing `: | grep "$1" "" >/dev/null 2>&1` **always** return `false` on _bash_ `5.2.15(1)-release (x86_64-pc-linux-gnu)` @ _linux_ `6.1.0-25-amd64`.
It causes problems like:
- no color for matches
- including undesired directories

grep - fix option availability check.

---

plugins/starship/README.md
plugins/starship/starship.plugin.sh

close my own issue: https://github.com/ohmybash/oh-my-bash/issues/627
I believe I didn't do anything wrong in the code
----
Closes #627

[Plugin] adding starship

---

README.md

docs: fix links to CONTRIBUTING.md and CODE_OF_CONDUCT.md
A difference in capitalization caused the link from the readme to the contributing doc to be broken, and an extra set of back-ticks caused the link from the readme to the code of conduct to be broken.

docs: fix links to CONTRIBUTING.md and CODE_OF_CONDUCT.md

---

completions/ssh.completion.sh

Also find 'host myhost' and 'HOST myhost' in ssh-config

Update ssh.completion.sh to be case-insensitive

---

plugins/progress/README.md
plugins/progress/progress.plugin.sh

This change improves the progress plugin by...
- Allows reseting the progress bar to allow running another progress bar after the first one is done
- Replaces the message whitespace so that there's no overlap in messages
- Scopes the variables within the function
- Renames the global variable so that it's namespaced a bit
Here's a good way to test it...
``` bash
progress 0 "Doing something cool!" && progress 40 "Hello?" && progress 60 "Almost done" && progress 100 "Close" && delay
```

progress: Improve the Progress Plugin

---

README.md
lib/omb-prompt-base.sh
templates/bashrc.osh-template
themes/font/font.theme.sh

[Spack](https://spack.io/) is a packaging manager allowing to create an environment (like Python virtual environment).
I added a function allowing the display of the spack environment name in the prompt.
The theme `font` was also updated with this modification (see the screenshot above - I have modified the colors on my local installation, but not on this version !)
Note that if Spack is not installed, this should not cause any error (at least it did not on my local tests)
I found issue #259 about this, but no actual solution was proposed (actually, I think he just did what I have done on his local installation :wink:)
I tried to follow the coding guidelines, if there is something that need to be improved, just tell me :)

feat: add spack environment in prompt

---

plugins/git/git.plugin.sh

This commit improves the Git plugin in Oh My Bash by adding autocompletion support for various Git aliases. The enhancements include:
- Adding `__git_complete` for multiple Git aliases to improve shell autocompletion.
- Ensuring better developer experience by providing context-aware suggestions for Git commands.
- Improving efficiency when using Git shortcuts by enabling autocompletion where applicable.
These changes enhance usability, making it easier for users to navigate and execute Git commands quickly.
Fixes: #658, #633

feat(git): add autocompletion for git aliases in git.plugin.sh

---

plugins/nvm/nvm.plugin.sh

When checking the version in the resolved `.nvmrc` file found, the
change made in d2163a6 tried to read the file a second time, but did not
use the resolved `$nvm_path` but rather tried to simply read it from the
current directory. This fails if the file was resolved to a parent
directory.
This change updates the code to reuse the version value which was read
from the file two lines prior.

fix(plugins/nvm): Correctly handle `.nvmrc` in a parent directory.

---

custom/aliases/example.aliases.sh

adding explanation on how to practically use './custom/aliases/example.aliases.sh'

adding explanation to 'example.aliases.sh'
