ohmybash/oh-my-bash

- plugins/core/core.plugin.sh
> Fixed issue #11

- themes/agnoster/agnoster-bash.theme.sh
- themes/agnoster/agnoster.base.sh
Fixes #45 
This agnoster theme script is taken from https://github.com/speedenator/agnoster-bash.
> adding agnoster theme files

- CODE_OF_CONDUCT.md
> Oh My Bash - Code of Conduct

- completions/git.completion.sh
This one fixes the git completion for main commands (e.g. git {TAB][TAB])
> Fix git commands completion

- README.md
Removed section which discourages contribution
> README : Remove dicouraging/inappropriate section

- completions/maven.completion.sh
This is a proposal to replace maven completion with the one form :
- https://github.com/juven/maven-bash-completion
- https://github.com/parisjug/maven-bash-completion
> update maven completion

- plugins/bashmarks/bashmarks.plugin.sh
> plugins/bashmark: resolves conflict between noclobber and bashmark

- plugins/git/git.plugin.sh
> plugins/git: Add git cherry-pick -s

- plugins/nvm/README.md
- plugins/nvm/nvm.plugin.sh
- plugins/sdkman/README.md
- plugins/sdkman/sdkman.plugin.sh
- added the `nvm` and `sdkman` as plugin
- added the readme docs with installation and configuration st
> feat(plugins): added nvm and sdkman as plugins

- themes/garo/garo.theme.sh
Yet another extra theme...
I use it, but it's nothing special. You'll probably don't want it.<br>Don't worry, I won't be offended :smiley: 
It's just a smaller version of the `font` theme.
> Extra theme 'garo'

- plugins/ansible/README.md
- plugins/ansible/ansible.plugin.sh
**Feature**
1. Ansible plugin implemented
> plugins/ansible: Ansible plugin added

- completions/minikube.completion.sh
Add Kubernetes minikube completion script
> completions/minikube: Add minikube completion

- README.md
References: #52 
Credit: @scottsword
> README: Update links for screenshots

- plugins/ansible/README.md
- plugins/ansible/ansible.plugin.sh
- plugins/brew/README.md
- plugins/brew/brew.plugin.sh
- plugins/kubectl/README.md
- plugins/kubectl/kubectl.plugin.sh
- plugins/npm/README.md
- plugins/npm/npm.plugin.sh
**Plugins**
1. Kubectl
2. Brew
3. NPM
> plugins: Multiple plugins implemented

- plugins/ansible/README.md
A small type error fixed on the README.md file
> Typo: Fixed

- plugins/sdkman/README.md
- plugins/sdkman/sdkman.plugin.sh
- Update plugin comments to match sdkman
- Update sdkman plugin README links
> Fix sdkman plugin comments

- plugins/zoxide/README.md
- plugins/zoxide/zoxide.plugin.sh
[zoxide](https://github.com/ajeetdsouza/zoxide) a smart, fast, and configurable alternative to your cd command.
> plugins: add plugin for zoxide

- completions/makefile.completion.sh
> completions/make: Supporting GNUmakefile and makefile

- tools/install.sh
> tools/install: Support `--unattended` option

- lib/grep.sh
Fixed an error in the parameter substitution from previous pull request.
----
**edit** by @akinomyoga
Fixes #229
> Grep alias

- plugins/battery/battery.plugin.sh
> Correction for grep regex when upower is used

- plugins/battery/battery.plugin.sh
- themes/kitsune/kitsune.theme.sh
> Fix kitsune.theme and battery.plugin

- plugins/tmux-autoattach/tmux-autoattach.plugin.sh
this corrects the plugin not connecting back to the session by default
> Fix Tmux-autoattach plugin to reattach to a session is there is one

- plugins/vagrant/README.md
- plugins/vagrant/vagrant.plugin.sh
Create a new plugin to work with vagrant environments, its easy to use.
> Vagrant plugin creation for OMB

- plugins/ansible/ansible.plugin.sh
- plugins/vagrant/README.md
- plugins/vagrant/vagrant.plugin.sh
Feature to connect over vagrant servers
Fix in Ansible plugin description
> Feature to connect over vagrant servers

- lib/history.sh
- templates/bashrc.osh-template
Make HIST_STAMPS works
fix #233 
add color to the timestamp field in history
> Make HIST_STAMPS works and add color to history

- plugins/nvm/README.md
- plugins/nvm/nvm.plugin.sh
> plugins/nvm: add nvmrc autoload option

- plugins/gcloud/README.md
- plugins/gcloud/gcloud.plugin.sh
This plugin provides support for gcloud and loads its completions
> feat: adding gcloud plugin

- lib/shopt.sh
- templates/bashrc.osh-template
Solving the issue #137 changed the template and where the case sensitive attribute was defined
> lib/shopt: Add support for CASE_SENSITIVE

- themes/rr/rr.theme.sh
Resolve #372.
I create a PR for the change suggested in https://github.com/ohmybash/oh-my-bash/issues/372#issuecomment-1325678142
Ref: https://github.com/ohmybash/oh-my-bash/pull/393#issuecomment-1416783536
> themes/rr: Add Python virtual environments

- completions/crc.completion.sh
- completions/helm.completion.sh
- completions/oc.completion.sh
- completions/tkn.completion.sh
> Add completion files for OpenShift/K8s tools

- lib/base.sh
- oh-my-bash.sh
- themes/agnoster/agnoster.theme.sh
Small correctness improvements.
> fix: Small syntax improvements

- lib/history.sh
Just an absolute minor fix of correcting a broken link in comments.
> Fixed broken link in comments

- plugins/sudo/README.md
- plugins/sudo/sudo.plugin.sh
Simple sudo plugin to add sudo at the beginning of the line or with last command executed if line is empty.
> sudo plugin

- aliases/general.aliases.sh
- lib/bourne-shell.sh
- lib/utils.sh
* Without this fix `ls` output is not colored on all systems
> lib/theme-and-appearance: Fix broken ls-colors

- plugins/sudo/sudo.plugin.sh
Hi!
In this PR I've created the functionality of toggling `sudo` and fixed a bug that when you press `<ESC>` four times or more it was just adding more and more `sudo` commands to the begin.
> plugins/sudo: Added toggle support

- plugins/git/git.plugin.sh
Useful for visual side by side diff VIA external difftool. Here is an example for meld: https://stackoverflow.com/questions/2006032/view-differences-of-branches-with-meld
> feat(git.plugin): adding alias to open predefined difftool

- themes/kitsune/kitsune.theme.sh
last change does not working.so i do some change in this theme
> virtual enviroment add in kitsune theme

- aliases/package-manager.aliases.bash
Add commands so the DNF is supported for alliases.
> aliases/package-manager: Add Fedora Commands to package-manager.alliases.bash

- aliases/README.md
- aliases/package-manager.aliases.bash
Added Nala aliases, reflected changes in README.md, added detailed descriptions for package managers to README.md
----
Continued from PR #460 (which was unexpectedly closed)
> aliases/package-manager: Add nala aliases

- plugins/bashmarks/bashmarks.plugin.sh
Refactor broke completion for bm without any arguments
> Fix bashmarks completion

- README.md
- oh-my-bash.sh
- templates/bashrc.osh-template
Mirror discussion:
Mirror solution: https://github.com/ohmyzsh/ohmyzsh/commit/3d4890dcc07478e7129de1e79afedafd3f08ffbc
> themes/random: Blacklisting Themes

- aliases/chmod.aliases.sh
> Clarify comments for `chmod` aliases

- themes/bakke/bakke.theme.sh
I modified the python venv to be visible in the terminal (Refer to #457).
> themes/bakke: Modify - python venv to be visible

- themes/robbyrussell/robbyrussell.theme.sh
_- Added python venv tag (env) support ._
Fixes #534
> Robby russel theme update

- themes/wanelo/wanelo.theme.sh
> fix(themes/wanelo): localize variable `status`

- plugins/README.md
- plugins/cargo/README.md
- plugins/cargo/cargo.plugin.sh
Added a plugin for working with cargo, made aliases for cargo itself and also for the most frequently used commands.
> plugins/cargo: Added a new plugin for working with cargo

- plugins/README.md
- plugins/rbenv/README.md
- plugins/rbenv/rbenv.plugin.sh
Added a new plugin for working with rbenv. It registers the necessary paths, initializes the environment, and sets a useful alias.
> plugins/rbenv: Added a new plugin for working with rbenv

- lib/omb-prompt-base.sh
- themes/ht/ht.theme.sh
Fixed python and ruby environments printing to prompt for ht theme.
> themes/ht: Fixed env printing

- plugins/README.md
- plugins/dotnet/README.md
- plugins/dotnet/dotnet.plugin.sh
This PR is copying the dotnet plugin from oh-my-zsh. This plugin is handy for dotnet developers.  I used it so much in oh-my-zsh that I had to add it here.
> New Plugin for dotnet CLI

- completions/uv.completion.sh
completions: add uv python package and project manager
> completions: add uv python package and project manager

- aliases/package-manager.aliases.bash
- aliases/package-manager.aliases.md
Add aliases for the Snap package manager.
Close #686
> feat(aliases/package-manager): add aliases for snap

- plugins/README.md
- plugins/virtualenvwrapper/README.md
- plugins/virtualenvwrapper/virtualenvwrapper.plugin.sh
Add a plugin to load virtualenvwrapper.
Virtualenvwrapper is a set of extensions to the python virtualenv tool, and includes wrappers for creating and deleting virtual environments and otherwise managing your python development workflow.
> feat(plugins): add virtualenvwrapper plugin
